name: avatar
on:
  push:
    branches:
      - main

jobs:
  avatar:
    name: avatar
    runs-on: ubuntu-20.04
    steps:
      - name: clone codes
        env:
          REPO_CODE: ${{ secrets.CODING_REPO_PREFIX }}/avatar/code.git
          REPO_IMG: ${{ secrets.CODING_REPO_PREFIX }}/avatar/image.git
        run: |
          git clone $REPO_CODE
          git clone $REPO_IMG
      - name: run codes
        run: |
          cd code
          python3 run.py -s ${{ secrets.AVATAR_START }} -e ${{ secrets.AVATAR_END }}
      - name: push
        run: |
          git config --global user.name "SunYufei"
          git config --global user.email "sunyufei963@qq.com"
          cd image
          git add .
          git commit -m "Pushed by GitHub Actions"
          git push
