name: autorun
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,1,2,3,4,5,6,15,16,17,18,19,20,21,22,23 * * *'

jobs:
  autorun:
    name: autorun
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: pip3 install requests lxml
      - name: Run codes
        run: python3 run.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
