name: autorun
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0-6,15-23 * * *'

jobs:
  autorun:
    name: autorun
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip3 install requests lxml
      - name: run code
        run: python3 run.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
